name: Test

on:
  push:
    branches:
    - main
    paths:
    - '.github/workflows/test.yml'
    - 'poc/**'
  pull_request:
    paths:
    - '.github/workflows/test.yml'
    - 'poc/**'

jobs:
  test:
    name: "Run unit tests for reference code"
    runs-on: ubuntu-latest
    container:
      image: sagemath/sagemath:latest
      options: --user root

    steps:
    - name: Install git on container
      run: |
        apt update
        apt install -y git

    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Install dependencies
      run: sage --pip install pycryptodomex

    - name: Run tests
      working-directory: poc
      run: sage -python -m unittest *_test.py
